### PR TITLE
[CLOUD-2304] [Don't Merge] Upgrade images for 6.4.8.

### PR DESCRIPTION
**Pull request by antncl**
Signed-off-by: Ant Stephenson <anstephe@redhat.com>
(cherry picked from commit d45d883a5e03b7760aae94457a0cec98b5b78f60)

### CODE REVIEW

**Comment by goldmann** [comment]
If this is a CP, it should go to CP branch.

**Comment by goldmann** [comment]
Ok, I see now the other PR. You should not open 2 PRs for dev and cp. After release from CP branch you should merge it into dev branch, not sooner. This PR should be closed.

**Comment by antncl** [comment]
Right - I'll just leave this open until after they're signed off.

**Comment by goldmann** [comment]
This can get very easily out of control, but you are the maintainer now ;)

**Pull request closed without merging**
