### PR TITLE
[CLOUD-2304] Upgrade images for 6.4.8.

### PR DESCRIPTION
**Pull request by antncl**
Signed-off-by: Ant Stephenson <anstephe@redhat.com>

### CODE REVIEW

**Review by errantepiphany — CHANGES_REQUESTED** [review]
BPMSUITE_PATCH_VERSION has to be updated too: https://github.com/AntStephenson/jboss-kieserver-6-openshift-image/blob/d45d883a5e03b7760aae94457a0cec98b5b78f60/image.yaml#L123-L124

**Comment by antncl** [comment]
@errantepiphany Done. Sorry I missed that!

**Review by errantepiphany — APPROVED** [review]

**Comment by errantepiphany** [comment]
@AntStephenson : No worries. @pszubiak : Did you want to take a look before this gets merged?

**Review by pszubiak — APPROVED** [review]
+1 looks good

**Pull request merged**
