### PR TITLE
[CLOUD-2235] add jboss-kie-modules repo

### PR DESCRIPTION
**Pull request by psiroky**
@goldmann @spolti aaaand one more....

### CODE REVIEW

**Review by spolti — APPROVED** [review]

**Comment by goldmann** [comment]
This is, generally speaking wrong. The cp and la branches should point to a ref that will not change. Imagine if we would do a rebuild, we cannot fetch new changes. Please think about it.

**Comment by goldmann** [comment]
One solution could be to release the initial module, for example as 1.0 and reference it that way.

**Comment by psiroky** [comment]
I agree this is wrong. But this PR does not actually make it worse, it was wrong even before :)

We can release (tag) the module as 1.0 I think as reference that.

**Comment by goldmann** [comment]
I agree that it was wrong even before ;)

Let's do it in the following way: let's merge this and we will fix it tomorrow, when you decide what versioning scheme you want to use. Sounds like a plan?

**Comment by psiroky** [comment]
@goldmann sounds good :) -- although it could take some time until we figure out how to version things.

**Pull request closed without merging**
